global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'voucher-api'
    static_configs:
      - targets: ['api:9090']
        labels:
          service: 'voucher-api'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
